---
title: "Welcome to The Graduate Student Perspective"
description: |
author:
  - name: Md Ferdous Alam
    url: https://ferdous-alam.github.io
    affiliation: PhD student, MAE, The Ohio State University
    affiliation_url: https://mae.osu.edu
date: 03-29-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
## Why graduate student perspective?
Machine learning, Reinforcement learning and control theory are vast! The stream of research articles are often overwhelming. Sometimes I like to take a step back and surprisingly I find peace exploring fundamental topics and explaining them. I remeber there was a time when I wanted a blog that explains complex topics in intuitive ways. Now-a-days the chaotic stream of online blogs have made it extremely difficult for me to find a reliable blog post quickly. I personally enjoy a nice balance between formal presentation of concepts (because they are robust!) followed by an interesting toy example for building intuitions. I like to call this approach **Intuitive formalism** or often during my PhD research presentations I use the term **visual formalism**. Unfortunately I can not find a lot of online blog posts/writings according to my taste. So I decided to make a blog for myself that gave birth to this site. In the unlikely case of you reading this I appreciate your time here. Cheers! :) 



