---
title: "Transformer implementation deconstructed"
header-includes:
  - \usepackage{float}
  - \floatplacement{figure}{!htb}
  - \usepackage{algorithm}
  - \usepackage{algpseudocode}
  
description: |
  A cheat sheet for implementing transformers.
  
output:  
  distill::distill_article:
    toc: true
    toc_depth: 2

date: 08-21-2022
author:
  - name: Md Ferdous Alam
    url: https://ferdous-alam.github.io
    affiliation: PhD student, MAE, The Ohio State University
    affiliation_url: https://mae.osu.edu

bibliography: biblio.bib

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

> **_NOTE:_** Code implementation can be found at this [repo](https://github.com/ferdous-alam/DeconstructedML/tree/master/Deconstructed_Deep_learning/Transformers).

## Introduction
Few symbols: 

  | symbol | tensor shape | description |
  | -----  | ----- | ------- |
  | $B$ | - | batch size | 
  | $l_z$ | - | context/source sequence length | 
  | $l_x$ | - | primary/target sequence length | 
  | $d_\text{model}$ | - | input dimension |
  | $d_k$ | - | dimension of query/key embedding | 
  | $d_v$ | - | dimension of value embedding | 
  | $B$ | - | batch size | 
  | $h$ | - | number of heads | 
  | $LN$ | - | layer norm | 
  | $FFN$ | - | feed forward network | 
  | $\mathbf{Z}$ | $(B, l_z, d_\text{model})$ | context/source sequence | 
  | $\mathbf{X}$ | $(B, l_x, d_\text{model})$ | primary/target sequence | 
  | $\mathbf{M}_{zz}$ | $(l_z, l_z)$ | source mask | 
  | $\mathbf{M}_{xx}$ | $(l_x, l_x)$ | target mask |
  | $\mathbf{M}_{zx}$ | $(l_z, l_x)$ | memory mask |
  | $L_{enc}$ | - | number of encoder layers |
  | $L_{dec}$ | - | number of decoder layers |
  
  
We start with the originally proposed encoder-decoder (ED) transformer [cite]. If we only use the encoder of the transformer, then it is similar to the BERT [cite] model and if we only use the decoder of the transformer then it is similar to the GPT model [cite]. For clarity, we consider a batched source sequence data $\mathbf{Z}$ which consists of $B$ sequences. Each sequence is of length $l_z$. This means that the sequence consists of $l_z$ number of tokens or vector representation of some input.

$$ \mathbf{Z} = \begin{bmatrix} \mathbf{z}^1_1 & \mathbf{z}^1_2 & \dots & \mathbf{z}^1_{l_z} \\ 
                \mathbf{z}^2_1 & \mathbf{z}^2_2 & \dots & \mathbf{z}^2_{l_z} \\ 
                \vdots & \vdots & \vdots & \vdots \\
                \mathbf{z}^{B}_1 & \mathbf{z}^{B}_2 & \dots & \mathbf{z}^{B}_{l_z}
                \end{bmatrix}$$
                
where, $$\mathbf{z}_i \in \mathbb{R}^{1\times d_\text{model}}, \ \ \ \ \ i = 1, 2, \dots, l_z$$
                
Similarly, we consider a batched target sequence data $\mathbf{X}$ that contain $B$ sequences in total. Each target sequence is of length $l_x$.

$$ \mathbf{X} = \begin{bmatrix} \mathbf{x}^1_1 & \mathbf{x}^1_2 & \dots & \mathbf{x}^1_{l_x} \\ 
                \mathbf{x}^2_1 & \mathbf{x}^2_2 & \dots & \mathbf{x}^2_{l_x} \\ 
                \vdots & \vdots & \vdots & \vdots \\
                \mathbf{x}^{B}_1 & \mathbf{x}^{B}_2 & \dots & \mathbf{x}^{B}_{l_x}
                \end{bmatrix}$$

where, $$\mathbf{x}_i \in \mathbb{R}^{1\times d_\text{model}}, \ \ \ \ \ i = 1, 2, \dots, l_x$$

The goal is to learn a representation of the target sequence, $\mathbf{X}$, that utilizes multi-head attention to capture important correlation within the sequence. Finally, people use these representations for various downstream tasks i.e. machine translation [cite], next word prediction [cite], computer vision [cite], reinforcement learning [cite] etc. 

### Mask

$$\text{Mask}[t_z, t_x] = \begin{cases} 1 \quad \quad \quad \quad  \text{for bidirectional attention} \\ [[t_z \leq t_x]]  \quad \text{for unidirectional attention} \end{cases}$$


## Formal algorithm 
First we provide a pseudoode of the encoder-decoder transformer algorithm. The following pseudocode is a simplified version of the formal algorithm presented in this paper [cite]. Initially I wanted to include the original pseudocode from the paper. But it seems like a handling a lot of notations while thinking of implementation. So, I added some trivial abstraction on top of that so the implementation becomes more convenient.

### Encoder-decoder transformer
| Algorithm 1: Encoder Decoder Transformer|
| :---      |
| input: $\mathbf{Z} \in \mathbb{R}^{l_z \times d_\text{model}}$,  $\mathbf{X} \in \mathbb{R}^{l_x \times d_\text{model} }$, vector representations of context and primary sequence, $L_{enc}$, $L_{dec}$, number of encoder and decoder layers, EncoderLayer class, DecoderLayer class, source_mask, target_mask, memory_mask|
| output: $\mathbf{X} \in \mathbb{R}^{l_x \times d_\text{model}}$, representation of primary sequence with multi-head attention which can be used for downstream applications|
| 1  For $i = 1, 2, \dots, L_{enc}$|
| 2  $\quad  \mathbf{Z} \leftarrow \text{EncoderLayer}(\mathbf{Z}, \mathbf{M}_{zz}: Optional)$ |
| 3  $\text{memory} = \mathbf{Z}$|
| 4  For $j = 1, 2, \dots, L_{dec}$|
| 5  $\quad  \mathbf{X} \leftarrow \text{DecoderLayer}(\mathbf{X}, \text{memory}, \mathbf{M}_{xx}: Optional, \mathbf{M}_{zz}: Optional, \mathbf{M}_{zx}: Optional)$|


> **_Implementation note:_**  For efficiency, deepcopy of a single encoder and decoder layer can be performed $L_{enc}$ and $L_{dec}$ times

The training procedure is fairly simple and basically same as other neural network models. To make a broaded sense, I am not including any NLP specific output from the model. So, the output from the model is what we are interested in. We will also need to supply the target so that loss can be caluculated using the output and the target values. Finally we perform gradient descent to minimize the loss. 

### Training procedure 
| Algorithm 4: Training Transformer|
| :------------------ |
| $\text{input: } \text{class EDTransformer, class loss_func, learning rate $\eta$}$ |
| 1  $\text{for } i = 1, 2, \dots, N_\text{epochs}$|
| 2  $\quad \text{for } (\mathbf{Z}, \mathbf{X}, \text{target}) \text{ in train_dataloader } \quad \quad \text{# typical data loader for training data}$|
| 3  $\quad \quad  output \leftarrow \text{EDTransformer}(\mathbf{Z}, \mathbf{X}, \mathbf{M}_{xx}: Optional, \mathbf{M}_{zz}: Optional, \mathbf{M}_{zx}: Optional)$|
| 4  $\quad \quad \mathcal{L}(\mathbf{\theta}) = \text{loss_func}(\text{output, target})$|
| 5  $\quad \quad \theta \leftarrow \theta - \eta \cdot \nabla\mathcal{L}(\theta)$|
| 6  $\text{return } \mathbf{\theta}$|


## Attention 
Transformers use multi-head attention to learn the contextual information of a sequence.

### Multihead attention
The original $Q, K, V$ matrices are projected into $h$ smaller matrices of using parameter matrices $W_i^Q, W_i^K, W_i^V$. Then attention is calculated for all these smaller matrices and concatened again to calculate attention for the full size input. 

  | argument | tensor shape |
  | ------ | -------- |
  | query $Q$ | $(B, l_x, d_\text{model})$ |
  | key, $K$ | $(B, l_z, d_\text{model})$ |
  | value, $V$ | $(B, l_z, d_\text{model})$ |
  | $\text{multi_attn}$ | $(B, l_x, d_\text{out})$ |



Let's recall the original definition of multi-head attention: 
$$\text{Multi-head attention, }\mathbf{Y}(Q, K, V) = [\mathbf{S}_1; \dots; \mathbf{S}_h]W^O$$
where $\mathbf{S}_i$ is the $i$-th single head attention score. 

As we are dividing the original $Q, K, V$ matrices into smaller matrices, dimension of $Q, K, V$ must be divisible by the number of heads, $h$. This is one way to do that if we want to divide $Q, K, V$ into the same dimension of smaller matrices.
$$ d_k = d_v = d_\text{model} / h$$ 
Alternatively, we can divide $Q, K, V$ into different dimensions of smaller matrices as long as they match the original dimension.  
 

  | Parameters | dimension |
  | -----  | ----- |
  | query projection FFN, $W^Q$ | $\mathbb{R}^{d_\text{model}\times d_k}$ | 
  | key projection  FFN, $W^K$ |$\mathbb{R}^{d_\text{model}\times d_k}$ | 
  | value projection  FFN, $W^V$ | $\mathbb{R}^{d_\text{out}\times d_v}$ |
  | output projection  FFN, $W^O$ | $\mathbb{R}^{hd_v\times d_\text{out}}$ |
  
So, these parameter weight matrices help to project the original $Q, K, V$ into smaller $h$ number of $q, k, v$ matrices for multi-head purpose.
$$\text{query projection, }W_i^Q: Q \rightarrow \mathbf{q}_i$$
$$\text{key projection, }W_i^K: K \rightarrow \mathbf{k}_i$$
$$\text{value projection, }W_i^V: V \rightarrow \mathbf{v}_i$$
For efficient implementation we calculate the attention score for all heads simultaneously by reshaping the tensors. So, the shape of the smaller tensors end up being the following, 

|tensor| expression | shape | efficient implementation |
| ----- |------------- | ------- | ----- | 
| $\mathbf{q}_i$ | $QW^Q_i$ | $(B, l_x, d_k)$  | $(B, h, l_x, d_k)$ | 
| $\mathbf{k}_i$ | $KW^K_i$ | $(B, l_z, d_k)$  | $(B, h, l_z, d_k)$ |
| $\mathbf{v}_i$ | $VW^V_i$ | $(B, l_z, d_v)$  | $(B, h, l_z, d_v)$ |

Note that, for efficient implementation, we calculate $\mathbf{q}_i, \mathbf{k}_i, \mathbf{v}_i$ for all heads simulatenously. 

### Scaled dot product attention
Now, we can calculate attention score, not attention values, using the originally proposed formula

$$\mathbf{S}_i(Q, K, V) = \text{softmax}\left(\frac{q_ik_i^T}{\sqrt{d_k}}\right)v_i$$
Next we concatenate all the attention score to get the original dimension, 
$$\mathbf{S} \leftarrow [\mathbf{S}^1, \mathbf{S}^2, \dots, \mathbf{S}^h]$$

> **_Implementation note:_**  For efficiency, we can implement the heads simultaneously by reshapin the tensors, no need to concat later either

Finally, the attention values would be the following, 
$$\mathbf{Y} = \mathbf{S}\mathbf{W}^O$$
Shape of the input and output tensors would be the follwoing 

| tensor | shape|
| ----- | ----- |
|  $\mathbf{S}$ | $(B, l_x, h*d_v)$ |
|  $\mathbf{Y}$ | $(B, l_x, d_\text{out})$ |


### Self attention, cross-attention
Depending on how we create $Q, K, V$ we can define two types of attention mechanism. 

  1. self-attention: Same input, i.e. $\mathbf{X}$ or $\mathbf{Z}$ is used to represent all three matrices, so 
  $$\begin{matrix} \mathbf{Q} = \mathbf{X} \\ \mathbf{K} = \mathbf{X} \\ \mathbf{V} = \mathbf{X} \end{matrix}$$ 
  2. cross-attention: input, $\mathbf{X}$ is used to represent the query, but output from another encoder, called $\text{memory}$, is used to represent key and value, so  
  $$\begin{matrix} \mathbf{Q} = \mathbf{X} \\ \mathbf{K} = \text{memory} \\ \mathbf{V} = \text{memory} \end{matrix}$$


## Encoder
Each encoder layer consists of two elements, 1) self-attention and 2) feedforward network (FFN)

| Algorithm 2: Encoder Layer|
| :---      |
| input: encoder input $\mathbf{Z}$, $\text{class MultiheadAttention}$  |
|1 \ \ For $k = 1, 2, \dots, h$ |
|2 \ \ $\quad \mathbf{Z} = LN(\mathbf{Z} + \text{MultiheadAttention}(query=\mathbf{Z}, key=\mathbf{Z}, value=\mathbf{Z})))$ |

> **_Implementation note:_**  As we are implementing the heads simultaneously, the loop is not really needed.

## Decoder
Each decoder layer consists of three elements, 1) self-attention, 2) cross-attention and 3) feed forward network

| Algorithm 3: Decoder layer|
| :---      |
| input: decoder input $\mathbf{X}$, encoder output $\text{memory}$,  $\text{class MultiheadAttention}$ |
| 2 \ \ $\mathbf{X} = LN(\mathbf{X} + \text{MultiheadAttention}(query=\mathbf{X}, key=\mathbf{X}, value=\mathbf{X})))$ |
| 3 \ \ $\mathbf{X} = LN(\mathbf{X} + \text{MultiheadAttention}(query=\mathbf{X}, key=memory, value=memory))$ |
| 4 \ \ $\mathbf{X} = LN(\mathbf{X} + FFN(\mathbf{X}))$ |


## BERT and GPT
### Encoder transformer (BERT)
Now, we can define the BERT model in a very straightforward fashion. 

| Algorithm 2: Encoder Transformer|
| :---      |
| input: $\mathbf{X} \in \mathbb{R}^{l_x \times d_\text{model} }$, vector representations of primary sequence, $L_{enc}$, number of encoder layers, EncoderLayer class, $\mathbf{M}_{xx}$, target mask|
| output: $\mathbf{X} \in \mathbb{R}^{l_x \times d_\text{model}}$, representation of primary sequence with multi-head attention which can be used for downstream applications|
| 1  For $i = 1, 2, \dots, L_{enc}$|
| 2  $\quad  \mathbf{X} \leftarrow \text{EncoderLayer}(\mathbf{X}, \mathbf{M}_{xx}\equiv 1)$ |

Similarly, the GPT model can be presented as the following pseudocode. 

### Decoder transformer (GPT)
| Algorithm 2: Decoder Transformer|
| :---      |
| input: $\mathbf{X} \in \mathbb{R}^{l_x \times d_\text{model} }$, vector representations of primary sequence, $L_{enc}$, number of encoder layers, EncoderLayer class, $\mathbf{M}_{xx}$, target mask|
| output: $\mathbf{X} \in \mathbb{R}^{l_x \times d_\text{model}}$, representation of primary sequence with multi-head attention which can be used for downstream applications|
| 1  For $i = 1, 2, \dots, L_{dec}$|
| 2  $\quad  \mathbf{X} \leftarrow \text{DecoderLayer}(\mathbf{X}, \mathbf{M}_{xx}[t, t'] = [[t\leq t']])$ |




## Few remarks 
